"""mirgate to psql

Revision ID: 3c7ab41cef34
Revises: 91712c1dca6f
Create Date: 2026-06-04 16:10:21.653735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c7ab41cef34"
down_revision: Union[str, Sequence[str], None] = "91712c1dca6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "apps",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True
    )
    op.alter_column(
        "apps", "name", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    op.alter_column(
        "apps", "token", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    op.alter_column(
        "apps", "added", existing_type=sa.BIGINT(), type_=sa.Integer(), nullable=False
    )
    op.alter_column(
        "apps",
        "refreshed",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        nullable=False
    )
    op.create_index(op.f("ix_apps_id"), "apps", ["id"], unique=False)
    op.alter_column(
        "users",
        "id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True
    )
    op.execute("ALTER TABLE users ALTER COLUMN user_id TYPE UUID USING user_id::uuid")
    op.alter_column("users", "user_id", nullable=False)
    op.alter_column(
        "users",
        "found_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP")
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        nullable=False,
        existing_server_default=sa.text("CURRENT_TIMESTAMP")
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True
    )
    op.alter_column(
        "users", "username", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        nullable=False
    )
    op.alter_column(
        "users",
        "followers",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        nullable=False
    )
    op.alter_column(
        "users",
        "following",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        nullable=False
    )
    op.alter_column(
        "users", "posts", existing_type=sa.BIGINT(), type_=sa.Integer(), nullable=False
    )
    op.alter_column("users", "verified", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "has_itdp", existing_type=sa.BOOLEAN(), nullable=False)
    op.execute("""
        CREATE OR REPLACE FUNCTION parse_uuid_list(s text) RETURNS uuid[] AS $$
        DECLARE
            result uuid[] := '{}';
            m text[];
        BEGIN
            IF s IS NULL OR s = '[]' OR s = '' THEN
                RETURN '{}'::uuid[];
            END IF;
            FOR m IN
                SELECT regexp_matches(
                    s,
                    '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
                    'gi'
                )
            LOOP
                result := array_append(result, m[1]::uuid);
            END LOOP;
            RETURN result;
        END;
        $$ LANGUAGE plpgsql IMMUTABLE;
    """)

    op.execute(
        "ALTER TABLE users ALTER COLUMN following_users TYPE UUID[] USING parse_uuid_list(following_users)"
    )
    op.alter_column("users", "following_users", nullable=False)

    op.execute(
        "ALTER TABLE users ALTER COLUMN followed_by_users TYPE UUID[] USING parse_uuid_list(followed_by_users)"
    )
    op.alter_column("users", "followed_by_users", nullable=False)

    op.execute("DROP FUNCTION parse_uuid_list(text)")
    op.alter_column(
        "users", "avatar", existing_type=sa.TEXT(), type_=sa.String(), nullable=False
    )
    op.alter_column("users", "exists", existing_type=sa.BOOLEAN(), nullable=False)
    op.drop_index(
        op.f("idx_16390_sqlite_autoindex_users_1"), table_name="users", if_exists=True
    )
    op.drop_index(
        op.f("idx_16390_sqlite_autoindex_users_2"), table_name="users", if_exists=True
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_unique_constraint(None, "users", ["username"])
    op.create_unique_constraint(None, "users", ["user_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_user_id_key", "users", type_="unique")
    op.drop_constraint("users_username_key", "users", type_="unique")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_index(
        op.f("idx_16390_sqlite_autoindex_users_2"), "users", ["username"], unique=True
    )
    op.create_index(
        op.f("idx_16390_sqlite_autoindex_users_1"), "users", ["user_id"], unique=True
    )
    op.alter_column("users", "exists", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "avatar", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "users",
        "followed_by_users",
        existing_type=sa.ARRAY(sa.UUID()),
        type_=sa.TEXT(),
        nullable=True
    )
    op.alter_column(
        "users",
        "following_users",
        existing_type=sa.ARRAY(sa.UUID()),
        type_=sa.TEXT(),
        nullable=True
    )
    op.alter_column("users", "has_itdp", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "users", "posts", existing_type=sa.Integer(), type_=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "users",
        "following",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        nullable=True
    )
    op.alter_column(
        "users",
        "followers",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        nullable=True
    )
    op.alter_column(
        "users",
        "display_name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=True
    )
    op.alter_column(
        "users", "username", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP")
    )
    op.alter_column(
        "users",
        "found_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("CURRENT_TIMESTAMP")
    )
    op.alter_column(
        "users", "user_id", existing_type=sa.Uuid(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True
    )
    op.drop_index(op.f("ix_apps_id"), table_name="apps")
    op.alter_column(
        "apps",
        "refreshed",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        nullable=True
    )
    op.alter_column(
        "apps", "added", existing_type=sa.Integer(), type_=sa.BIGINT(), nullable=True
    )
    op.alter_column(
        "apps", "token", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "apps", "name", existing_type=sa.String(), type_=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "apps",
        "id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
        autoincrement=True
    )
    # ### end Alembic commands ###
