"""create user.bio and user.banner

Revision ID: 8cb9494bba57
Revises: d58c1f872a09
Create Date: 2026-06-28 22:47:33.905939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb9494bba57'
down_revision: Union[str, Sequence[str], None] = 'd58c1f872a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('banner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'banner')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
