"""initial

Revision ID: 91712c1dca6f
Revises: 
Create Date: 2026-06-04 15:26:20.771231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91712c1dca6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_16390_sqlite_autoindex_users_1'), table_name='users')
    op.drop_index(op.f('idx_16390_sqlite_autoindex_users_2'), table_name='users')
    op.drop_table('users')
    op.drop_table('apps')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('added', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('refreshed', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_16397_ix_apps_id'))
    )
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('found_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followers', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('following', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('posts', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('has_itdp', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('following_users', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('followed_by_users', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exists', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('idx_16390_ix_users_id'))
    )
    op.create_index(op.f('idx_16390_sqlite_autoindex_users_2'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_16390_sqlite_autoindex_users_1'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###
