"""add epepuy

Revision ID: d58c1f872a09
Revises: fcec4c209420
Create Date: 2026-06-11 15:22:10.554444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd58c1f872a09'
down_revision: Union[str, Sequence[str], None] = 'fcec4c209420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epepuy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id')
    )
    op.create_index(op.f('ix_epepuy_id'), 'epepuy', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_epepuy_id'), table_name='epepuy')
    op.drop_table('epepuy')
    # ### end Alembic commands ###
