"""remove unique for username

Revision ID: fcec4c209420
Revises: be4fa20ee0ab
Create Date: 2026-06-09 12:54:11.499702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcec4c209420'
down_revision: Union[str, Sequence[str], None] = 'be4fa20ee0ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_17664_sqlite_autoindex_users_1'), table_name='users')
    op.drop_index(op.f('idx_17664_sqlite_autoindex_users_2'), table_name='users')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_17664_sqlite_autoindex_users_2'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_17664_sqlite_autoindex_users_1'), 'users', ['user_id'], unique=True)
    # ### end Alembic commands ###
